FROM nescirem/docker-jenkins-fortran:mpich
MAINTAINER nescirem <nescirem@gmail.com>
LABEL description="Docker base image for Fortran(with MPICH and CGNS library) CI builds"

USER root

RUN cd ~ && wget -c https://github.com/CGNS/CGNS/archive/v3.2.1.tar.gz
RUN tar -xzvf v3.2.1.tar.gz && rm -f v3.2.1.tar.gz
RUN cd CGNS-3.2.1/src && ./configure
RUN make && make install
RUN rm -rf ~/CGNS-3.2.1

USER jenkins
