FROM nescirem/docker-jenkins-fortran:latest
MAINTAINER nescirem <nescirem@gmail.com>
LABEL description="Docker base image for Fortran(with MPICH) CI builds"

USER root

RUN apt update 
RUN apt install -y mpich && \
    apt-get clean

USER jenkins
