FROM nescirem/docker-jenkins-fortran:latest
MAINTAINER nescirem <nescirem@gmail.com>
LABEL description="Docker base image for Fortran(with MPICH) CI builds"

USER root

RUN apt update && apt install -y mpich && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/usr/lib64/mpich/bin:${PATH}"

USER jenkins
