FROM nescirem/docker-jenkins-fortran:mpich
MAINTAINER nescirem <nescirem@gmail.com>
LABEL description="Docker base image for Fortran(with MPICH and CGNS library) CI builds"

USER root

RUN apt update 
RUN apt install -y libcgns3.3 libcgns-dev && \
    apt-get clean

USER jenkins
